"""
Travel match web app.
Run: python3 app.py
Then open http://localhost:5000 in your browser.

Requires hotels.json (generated by travellingai.py) in the same folder.
"""

import json
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import anthropic
import requests
from dotenv import load_dotenv
from flask import Flask, jsonify, render_template_string, request

load_dotenv(Path(__file__).parent / ".env")
ANTHROPIC_API_KEY = (os.getenv("ANTHROPIC_API_KEY") or "").strip()
SERPAPI_KEY = (os.getenv("SERPAPI_API_KEY") or "").strip()

HOTELS_FILE = Path(__file__).parent / "hotels.json"

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Claude helpers (duplicated from travellingai.py to keep app.py self-contained)
# ---------------------------------------------------------------------------

_SCORE_KEYS = ["novelty", "remoteness", "romance", "intensity", "visual_awe", "luxury", "story_worthiness"]

_SCORE_SYSTEM = """\
You are a travel-preference classifier. Given a user's travel desire and optionally what they want to avoid,
return ONLY a JSON object with exactly these keys:
  novelty, remoteness, romance, intensity, visual_awe, luxury, story_worthiness — integers 0 to 10
  budget_usd — total trip budget converted to USD, or 0 if not mentioned
  avoidances — a list of lowercase words/short phrases to screen out from hotel names, vibes and descriptions
               Examples: ["resort", "hostel", "family", "party", "shared", "chain", "corporate", "crowded", "golf"]
               Return [] if nothing to avoid.
No explanation, no markdown, no extra keys — just the JSON object."""

_PITCH_SYSTEMS = {
    "safe": """\
You are a travel writer. Write 2-3 sentences like a trusted friend who has been there and loved it.
Warm, reassuring, confident. The reader should feel: "I know I won't regret this."
No bullet points, no headers. Speak directly to the traveller.""",

    "gem": """\
You are a travel writer. Write 2-3 sentences like you are letting someone in on a rare secret find.
Excited, slightly conspiratorial. The reader should feel: "I need to tell everyone about this."
No bullet points, no headers. Speak directly to the traveller.""",

    "wildcard": """\
You are a travel writer. Write 2-3 sentences that are bold, honest, slightly provocative.
This place might not be for everyone — and that is the whole point.
The reader should feel: "This is the one that makes a real story."
No bullet points, no headers. Speak directly to the traveller.""",
}

_DIMENSION_MAP = [
    ("novelty",          "Novelty"),
    ("remoteness",       "Remoteness"),
    ("romance",          "Romance"),
    ("intensity",        "Intensity"),
    ("visual_awe",       "Visual Awe"),
    ("luxury",           "Luxury"),
    ("story_worthiness", "Story Worthiness"),
]


def feeling_to_scores(user_input: str) -> dict:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    msg = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=256,
        system=_SCORE_SYSTEM,
        messages=[{"role": "user", "content": user_input}],
    )
    text = msg.content[0].text.strip()
    if text.startswith("```"):
        parts = text.split("```")
        text = parts[1].lstrip("json").strip() if len(parts) > 1 else text
    raw = json.loads(text)
    scores = {k: int(raw[k]) for k in _SCORE_KEYS if k in raw}
    scores["budget_usd"]  = float(raw.get("budget_usd") or 0)
    scores["avoidances"]  = [str(a).lower() for a in (raw.get("avoidances") or [])]
    return scores


def _parse_price(price_str) -> float:
    import re
    nums = re.findall(r"[\d]+\.?\d*", str(price_str).replace(",", ""))
    return float(nums[0]) if nums else 0.0


def _passes_avoidance(hotel: dict, avoidances: list) -> bool:
    if not avoidances:
        return True
    text = " ".join([
        str(hotel.get("Name", "")),
        str(hotel.get("Vibe", "")),
        str(hotel.get("Destination", "")),
    ]).lower()
    return not any(term in text for term in avoidances)


def compute_match(rows: list, user_scores: dict) -> None:
    for row in rows:
        dist, dims = 0, 0
        for key, col in _DIMENSION_MAP:
            val = row.get(col)
            if isinstance(val, (int, float)):
                dist += abs(val - user_scores[key])
                dims += 1
        row["Match %"] = round((1 - dist / (dims * 10)) * 100) if dims else 0


def generate_pitch(user_feeling: str, hotel: dict, role: str = "safe") -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    listing = (
        f"Hotel: {hotel.get('Name', '')}\n"
        f"Destination: {hotel.get('Destination', '')}\n"
        f"Vibe: {hotel.get('Vibe', '')}\n"
        f"Stars: {hotel.get('Stars', '')}\n"
        f"Rating: {hotel.get('Rating', '')} ({hotel.get('Reviews', '')} reviews)\n"
        f"Price (total stay): {hotel.get('Price (total)', '')}\n"
        f"Scores — Novelty: {hotel.get('Novelty')}, Remoteness: {hotel.get('Remoteness')}, "
        f"Romance: {hotel.get('Romance')}, Intensity: {hotel.get('Intensity')}, "
        f"Visual Awe: {hotel.get('Visual Awe')}, Luxury: {hotel.get('Luxury')}"
    )
    msg = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=220,
        system=_PITCH_SYSTEMS.get(role, _PITCH_SYSTEMS["safe"]),
        messages=[{"role": "user", "content": f"Traveller's desire: {user_feeling}\n\n{listing}"}],
    )
    return msg.content[0].text.strip()


def select_all(hotels: list) -> list:
    by_match = sorted(hotels, key=lambda h: h.get("Match %", 0), reverse=True)

    top10 = by_match[:min(10, len(by_match))]
    safe = max(top10, key=lambda h: float(h.get("Rating") or 0))

    pool20 = [h for h in by_match[:min(20, len(by_match))] if h is not safe]
    gem = max(pool20, key=lambda h: (h.get("Novelty") or 0) + (h.get("Match %", 0) / 10)) if pool20 else by_match[1]

    pool50 = [h for h in by_match[:min(50, len(by_match))] if h is not safe and h is not gem]
    wildcard = max(pool50, key=lambda h: (h.get("Novelty") or 0) + (h.get("Intensity") or 0)) if pool50 else by_match[2]

    editorial_names = {safe.get("Name"), gem.get("Name"), wildcard.get("Name")}
    remaining = [h for h in by_match if h.get("Name") not in editorial_names]

    return [
        {**safe,     "_role": "safe"},
        {**gem,      "_role": "gem"},
        {**wildcard, "_role": "wildcard"},
    ] + [{**h, "_role": "match", "_rank": i + 4} for i, h in enumerate(remaining)]


# ---------------------------------------------------------------------------
# Live availability check via SerpAPI
# ---------------------------------------------------------------------------

def check_availability(hotel: dict, check_in: str, check_out: str, adults: int, rooms: int) -> dict:
    try:
        resp = requests.get(
            "https://serpapi.com/search",
            params={
                "engine": "google_hotels",
                "q": f"{hotel.get('Name', '')} {hotel.get('Destination', '')}",
                "check_in_date": check_in,
                "check_out_date": check_out,
                "adults": adults,
                "rooms": rooms,
                "currency": "USD",
                "api_key": SERPAPI_KEY,
            },
            timeout=20,
        )
        resp.raise_for_status()
        properties = resp.json().get("properties") or []
    except Exception:
        return {"available": None, "live_price": "", "live_price_per_night": "", "booking_url": "", "live_photo": ""}

    name_lower = hotel.get("Name", "").lower()
    for prop in properties:
        if name_lower in (prop.get("name") or "").lower():
            total   = prop.get("total_rate") or {}
            nightly = prop.get("rate_per_night") or {}
            # Direct Google Hotels entity link — specific to this exact hotel
            booking_url = prop.get("link") or ""
            # Fresh photo from live response
            live_photo = prop.get("thumbnail") or ""
            if not live_photo:
                images = prop.get("images") or []
                if images:
                    live_photo = images[0].get("thumbnail") or images[0].get("original") or ""
            return {
                "available": True,
                "live_price": total.get("lowest", ""),
                "live_price_per_night": nightly.get("lowest", ""),
                "booking_url": booking_url,
                "live_photo": live_photo,
            }
    return {"available": False, "live_price": "", "live_price_per_night": "", "booking_url": "", "live_photo": ""}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TravelMatch — Find Your Perfect Stay</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif;
    background: #FDF8F2;
    color: #2C2A26;
    min-height: 100vh;
  }

  /* ── HERO ── */
  .hero {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 60px 24px 140px;
    text-align: center;
    position: relative;
    overflow: hidden;
  }
  .hero::before {
    content: '';
    position: absolute;
    inset: 0;
    background:
      radial-gradient(ellipse 90% 60% at 50% 0%, rgba(251,183,105,0.18) 0%, transparent 65%),
      radial-gradient(ellipse 60% 40% at 90% 90%, rgba(87,185,189,0.12) 0%, transparent 60%);
    pointer-events: none;
  }

  .brand {
    font-size: 0.72rem;
    font-weight: 800;
    letter-spacing: 5px;
    text-transform: uppercase;
    color: #E07B45;
    margin-bottom: 52px;
  }

  .about {
    max-width: 540px;
    margin-bottom: 48px;
  }
  .about p {
    color: #8A8070;
    font-size: 0.97rem;
    line-height: 1.8;
  }
  .about p + p { margin-top: 8px; }

  .main-question {
    font-size: clamp(2rem, 4.5vw, 3rem);
    font-weight: 800;
    letter-spacing: -0.5px;
    line-height: 1.15;
    margin-bottom: 30px;
    color: #1E1B18;
  }

  /* Input bar */
  .input-box {
    width: 100%;
    max-width: 720px;
    background: #fff;
    border: 1.5px solid #E8DDD0;
    border-radius: 20px;
    display: flex;
    align-items: flex-end;
    padding: 14px 14px 14px 22px;
    gap: 12px;
    box-shadow: 0 4px 24px rgba(180,140,100,0.10);
    transition: border-color 0.2s, box-shadow 0.2s;
    text-align: left;
  }
  .input-box:focus-within {
    border-color: #E07B45;
    box-shadow: 0 4px 28px rgba(224,123,69,0.15);
  }
  textarea {
    flex: 1;
    width: 100%;
    background: transparent;
    border: none;
    outline: none;
    color: #2C2A26;
    font-size: 1rem;
    font-family: inherit;
    line-height: 1.6;
    resize: none;
    min-height: 26px;
    max-height: 160px;
    text-align: left;
    display: block;
  }
  textarea::placeholder { color: #C4B8A8; text-align: left; }

  .send {
    width: 38px; height: 38px;
    background: #E07B45;
    border: none;
    border-radius: 11px;
    cursor: pointer;
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.15s, transform 0.1s;
  }
  .send:hover { background: #C9633A; transform: scale(1.05); }
  .send:disabled { opacity: 0.3; cursor: default; transform: none; }
  .send svg { width: 17px; height: 17px; fill: #fff; }

  .suggestions {
    display: flex;
    gap: 8px;
    margin-top: 14px;
    flex-wrap: wrap;
    justify-content: center;
  }
  .sug {
    background: #fff;
    border: 1px solid #E8DDD0;
    color: #9A8E80;
    border-radius: 20px;
    padding: 5px 14px;
    font-size: 0.75rem;
    font-family: inherit;
    cursor: pointer;
    transition: border-color 0.15s, color 0.15s, background 0.15s;
    box-shadow: 0 1px 4px rgba(180,140,100,0.07);
  }
  .sug:hover { border-color: #E07B45; color: #E07B45; background: #FFF7F2; }

  .surprise-btn {
    background: linear-gradient(135deg, #57B9BD, #3A9EAF);
    border: none;
    color: #fff;
    border-radius: 20px;
    padding: 6px 16px;
    font-size: 0.75rem;
    font-weight: 700;
    font-family: inherit;
    cursor: pointer;
    letter-spacing: 0.3px;
    box-shadow: 0 2px 10px rgba(87,185,189,0.30);
    transition: opacity 0.15s, transform 0.1s;
  }
  .surprise-btn:hover { opacity: 0.88; transform: scale(1.04); }

  .avoid-wrap {
    width: 100%;
    max-width: 720px;
    margin-top: 10px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .avoid-label {
    font-size: 0.72rem;
    color: #C4B8A8;
    white-space: nowrap;
    flex-shrink: 0;
  }
  .avoid-input {
    flex: 1;
    background: transparent;
    border: none;
    border-bottom: 1px solid #E8DDD0;
    outline: none;
    color: #6A6058;
    font-size: 0.82rem;
    font-family: inherit;
    padding: 3px 0 4px;
    transition: border-color 0.2s;
  }
  .avoid-input::placeholder { color: #D4C8B8; }
  .avoid-input:focus { border-color: #C0A898; }

  .hint {
    margin-top: 10px;
    font-size: 0.76rem;
    color: #C4B8A8;
    letter-spacing: 0.3px;
  }

  /* ── RESULTS ── */
  #results { padding-bottom: 100px; }

  .loading {
    text-align: center;
    padding: 90px 24px;
    color: #B0A090;
  }
  .spinner {
    width: 42px; height: 42px;
    border: 3px solid #F0E8DE;
    border-top-color: #E07B45;
    border-radius: 50%;
    animation: spin 0.7s linear infinite;
    margin: 0 auto 22px;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
  .loading-title { font-size: 1rem; color: #8A8070; margin-bottom: 6px; }
  .loading-sub { font-size: 0.83rem; color: #C4B8A8; }

  .results-inner {
    max-width: 860px;
    margin: 0 auto;
    padding: 0 24px;
  }
  .results-label {
    text-align: center;
    margin-bottom: 40px;
    padding-top: 20px;
  }
  .results-label h2 { font-size: 1.4rem; font-weight: 800; color: #1E1B18; margin-bottom: 6px; }
  .results-label p  { color: #9A8E80; font-size: 0.88rem; }

  .cards { display: flex; flex-direction: column; gap: 28px; }

  :root {
    --safe-c:     #57B9BD;
    --gem-c:      #D4A843;
    --wildcard-c: #D95C47;
  }

  .card {
    background: #fff;
    border-radius: 22px;
    overflow: hidden;
    border: 1px solid #F0E8DE;
    box-shadow: 0 2px 20px rgba(180,140,100,0.09);
    transition: transform 0.2s, box-shadow 0.2s;
  }
  .card:hover { transform: translateY(-3px); box-shadow: 0 14px 44px rgba(180,140,100,0.17); }

  .card-banner {
    display: flex;
    align-items: center;
    gap: 9px;
    padding: 10px 22px;
    font-size: 0.67rem;
    font-weight: 800;
    letter-spacing: 2.5px;
    text-transform: uppercase;
    color: #fff;
  }
  .card-banner .banner-icon { font-size: 0.95rem; }
  .card[data-role="safe"]     .card-banner { background: var(--safe-c); }
  .card[data-role="gem"]      .card-banner { background: var(--gem-c); }
  .card[data-role="wildcard"] .card-banner { background: var(--wildcard-c); }
  .card[data-role="match"]    .card-banner { background: #B8A898; }

  .card-main { display: flex; }
  .card-img {
    width: 240px;
    min-width: 240px;
    object-fit: cover;
    display: block;
  }
  .card-img-placeholder {
    width: 240px;
    min-width: 240px;
    background: #FBF5EE;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.8rem;
  }
  .card-body {
    padding: 20px 26px;
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 12px;
  }
  .card-name { font-size: 1.15rem; font-weight: 800; line-height: 1.25; color: #1E1B18; }
  .card-dest { font-size: 0.82rem; color: #9A8E80; margin-top: 4px; }
  .match-pill {
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 0.76rem;
    font-weight: 700;
    white-space: nowrap;
    flex-shrink: 0;
    color: #fff;
  }
  .card[data-role="safe"]     .match-pill { background: var(--safe-c); }
  .card[data-role="gem"]      .match-pill { background: var(--gem-c); }
  .card[data-role="wildcard"] .match-pill { background: var(--wildcard-c); }
  .card[data-role="match"]    .match-pill { background: #B8A898; }

  .card-pitch { color: #5A5248; line-height: 1.82; font-size: 0.95rem; flex: 1; }

  .card-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-top: 4px;
  }
  .avail-badge {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-size: 0.72rem;
    font-weight: 700;
    padding: 3px 10px;
    border-radius: 20px;
    margin-bottom: 4px;
  }
  .avail-yes { background: #EDFAF3; color: #22A05A; }
  .avail-no  { background: #FEF0EE; color: #D95C47; }

  .criteria { display: flex; flex-wrap: wrap; gap: 6px; margin: 2px 0; }
  .crit {
    display: flex;
    align-items: center;
    gap: 5px;
    background: #FBF5EE;
    border-radius: 8px;
    padding: 3px 9px;
    font-size: 0.72rem;
    color: #9A8E80;
  }
  .crit-bar-wrap { width: 38px; height: 4px; background: #EDE5D8; border-radius: 2px; overflow: hidden; }
  .crit-bar { height: 100%; border-radius: 2px; background: #E07B45; }
  .crit-pct { font-weight: 700; color: #5A5248; min-width: 28px; text-align: right; }

  .refine-row { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 4px; }
  .refine-btn {
    font-size: 0.7rem;
    font-family: inherit;
    padding: 4px 11px;
    border: 1px solid #E8DDD0;
    background: transparent;
    border-radius: 20px;
    cursor: pointer;
    color: #9A8E80;
    transition: border-color 0.15s, color 0.15s, background 0.15s;
  }
  .refine-btn:hover { border-color: #E07B45; color: #E07B45; background: #FFF7F2; }

  /* Budget filter bar */
  .budget-bar {
    display: flex;
    align-items: center;
    gap: 10px;
    background: #FFF7F2;
    border: 1px solid #F0E8DE;
    border-radius: 14px;
    padding: 11px 20px;
    margin-bottom: 28px;
    flex-wrap: wrap;
  }
  .budget-bar-label { font-size: 0.82rem; color: #9A8E80; }
  .budget-input {
    background: #fff;
    border: 1.5px solid #E8DDD0;
    border-radius: 8px;
    padding: 5px 10px;
    font-size: 0.88rem;
    color: #2C2A26;
    font-family: inherit;
    width: 100px;
    outline: none;
    transition: border-color 0.2s;
    text-align: left;
  }
  .budget-input:focus { border-color: #E07B45; }
  .budget-apply {
    background: #E07B45;
    color: #fff;
    border: none;
    border-radius: 8px;
    padding: 6px 16px;
    font-size: 0.8rem;
    font-weight: 700;
    font-family: inherit;
    cursor: pointer;
    transition: background 0.15s;
  }
  .budget-apply:hover { background: #C9633A; }

  .card-price { font-size: 0.88rem; font-weight: 700; color: #9A8E80; }
  .book-link {
    padding: 9px 18px;
    color: #fff;
    border-radius: 10px;
    font-size: 0.82rem;
    font-weight: 700;
    text-decoration: none;
    transition: opacity 0.15s, transform 0.1s;
  }
  .book-link:hover { opacity: 0.85; transform: scale(1.03); }
  .card[data-role="safe"]     .book-link { background: var(--safe-c); }
  .card[data-role="gem"]      .book-link { background: var(--gem-c); }
  .card[data-role="wildcard"] .book-link { background: var(--wildcard-c); }
  .card[data-role="match"]    .book-link { background: #B8A898; }

  .error { color: #D95C47; text-align: center; padding: 70px 24px; font-size: 0.95rem; }

  /* Pagination */
  .pagination {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 40px 0 60px;
    flex-wrap: wrap;
  }
  .page-btn {
    background: #fff;
    border: 1.5px solid #E8DDD0;
    border-radius: 10px;
    padding: 8px 18px;
    font-size: 0.8rem;
    font-weight: 700;
    font-family: inherit;
    color: #9A8E80;
    cursor: pointer;
    transition: border-color 0.15s, color 0.15s;
  }
  .page-btn:hover:not(:disabled) { border-color: #E07B45; color: #E07B45; }
  .page-btn:disabled { opacity: 0.3; cursor: default; }
  .page-nums { display: flex; gap: 5px; align-items: center; }
  .page-num {
    width: 34px; height: 34px;
    background: #fff;
    border: 1.5px solid #E8DDD0;
    border-radius: 8px;
    font-size: 0.8rem;
    font-weight: 700;
    font-family: inherit;
    color: #9A8E80;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: border-color 0.15s, color 0.15s, background 0.15s;
  }
  .page-num:hover { border-color: #E07B45; color: #E07B45; }
  .page-num.active { background: #E07B45; border-color: #E07B45; color: #fff; }
  .page-ellipsis { color: #C4B8A8; font-size: 0.85rem; padding: 0 2px; }

  /* Two-person mode toggle */
  .mode-toggle {
    position: absolute;
    top: 22px;
    right: 28px;
    display: flex;
    align-items: center;
    gap: 7px;
    background: #fff;
    border: 1.5px solid #E8DDD0;
    border-radius: 20px;
    padding: 7px 16px;
    font-size: 0.75rem;
    font-weight: 700;
    color: #9A8E80;
    cursor: pointer;
    font-family: inherit;
    box-shadow: 0 1px 6px rgba(180,140,100,0.10);
    transition: border-color 0.15s, color 0.15s, background 0.15s;
    z-index: 10;
  }
  .mode-toggle:hover { border-color: #E07B45; color: #E07B45; }
  .mode-toggle.active { background: #E07B45; border-color: #E07B45; color: #fff; }

  /* Two-person input layout */
  .person-rows { display: none; flex-direction: column; gap: 0; flex: 1; }
  .person-rows.visible { display: flex; }
  .single-query { flex: 1; display: flex; align-items: center; min-width: 0; }
  .single-query.hidden { display: none; }

  .person-row {
    display: flex;
    align-items: flex-end;
    gap: 10px;
    padding: 8px 0;
  }
  .person-row + .person-row {
    border-top: 1px solid #F0E8DE;
  }
  .person-label {
    font-size: 0.7rem;
    font-weight: 800;
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #C4B8A8;
    white-space: nowrap;
    min-width: 58px;
  }
  .person-ta {
    flex: 1;
    background: transparent;
    border: none;
    outline: none;
    color: #2C2A26;
    font-size: 0.95rem;
    font-family: inherit;
    line-height: 1.6;
    resize: none;
    min-height: 24px;
    max-height: 100px;
    text-align: left;
  }
  .person-ta::placeholder { color: #C4B8A8; }
</style>
</head>
<body>

<div class="hero">
  <button class="mode-toggle" id="modeToggle" onclick="toggleMode()">👥 Two Person Mode</button>

  <div class="brand">TravelMatch AI</div>

  <div class="about">
    <p>We don't ask for dates or star ratings. We ask how you want to feel.</p>
    <p>Describe the experience you're after and we'll search 475 hotels across
       25 of the world's most extraordinary destinations — from Patagonia to Cappadocia —
       and find the ones that actually match you.</p>
  </div>

  <h1 class="main-question">What do you want to experience?</h1>

  <div class="input-box">
    <div class="single-query" id="singleQuery">
      <textarea id="query" rows="1"
        placeholder="e.g. I need something crazy and unusual. No luxury, only adventure."
        oninput="grow(this)"
        onkeydown="onKey(event)"></textarea>
    </div>
    <div class="person-rows" id="personRows">
      <div class="person-row">
        <span class="person-label">Person A</span>
        <textarea class="person-ta" id="query_a" rows="1"
          placeholder="What does Person A want to experience?"
          oninput="grow(this)" onkeydown="onKey(event)"></textarea>
      </div>
      <div class="person-row">
        <span class="person-label">Person B</span>
        <textarea class="person-ta" id="query_b" rows="1"
          placeholder="What does Person B want to experience?"
          oninput="grow(this)" onkeydown="onKey(event)"></textarea>
      </div>
    </div>
    <button class="send" id="btn" onclick="search()" title="Find matches">
      <svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>
    </button>
  </div>
  <div class="avoid-wrap">
    <span class="avoid-label">Avoid:</span>
    <input class="avoid-input" id="avoidances" type="text"
      placeholder="no huge resorts, not touristy, no shared bathrooms…"
      onkeydown="if(event.key==='Enter') search()">
  </div>

  <div class="suggestions">
    <button class="sug" onclick="suggest(this)">Something crazy &amp; adventurous</button>
    <button class="sug" onclick="suggest(this)">Unforgettable romantic trip</button>
    <button class="sug" onclick="suggest(this)">Remote escape, off the grid</button>
    <button class="sug" onclick="suggest(this)">A trip I'll still talk about at 80</button>
    <button class="surprise-btn" onclick="surprise()">✦ Surprise me</button>
  </div>
  <div class="hint">Press Enter to search &nbsp;·&nbsp; Shift+Enter for new line</div>
</div>

<div id="results"></div>

<script>
  let lastQuery      = '';
  let lastScores     = null;
  let baseScores     = null;
  let lastBudget     = 0;
  let lastAvoidances = [];
  let twoPersonMode  = false;

  // Pagination state
  const PAGE_SIZE    = 10;
  let allHotels      = [];
  let currentPage    = 0;
  let lastCheckIn    = '';
  let lastCheckOut   = '';
  let lastDisplayLabel = '';

  function toggleMode() {
    twoPersonMode = !twoPersonMode;
    const btn = document.getElementById('modeToggle');
    btn.classList.toggle('active', twoPersonMode);
    btn.textContent = twoPersonMode ? '✕ Single Mode' : '👥 Two Person Mode';
    document.getElementById('singleQuery').classList.toggle('hidden', twoPersonMode);
    document.getElementById('personRows').classList.toggle('visible', twoPersonMode);
  }

  const REFINE_SCORE_KEYS = {
    romantic:    'romance',
    adventurous: 'intensity',
    luxurious:   'luxury',
    remote:      'remoteness',
    unique:      'novelty',
    scenic:      'visual_awe',
  };

  function refine(dimension) {
    const base = baseScores || lastScores;
    if (!base) { search(); return; }
    const key = REFINE_SCORE_KEYS[dimension];
    const boosted = {...base, [key]: 10};
    search({ scores_override: boosted, budget_usd: lastBudget, avoidances_list: lastAvoidances });
  }

  function refineButtons(h) {
    const dims = [
      { key: 'romantic',    label: '+ More Romantic',    score: h['Romance'] },
      { key: 'adventurous', label: '+ More Adventurous', score: h['Intensity'] },
      { key: 'luxurious',   label: '+ More Luxurious',   score: h['Luxury'] },
      { key: 'remote',      label: '+ More Remote',      score: h['Remoteness'] },
      { key: 'unique',      label: '+ More Unique',      score: h['Novelty'] },
      { key: 'scenic',      label: '+ More Scenic',      score: h['Visual Awe'] },
    ];
    const lowest = dims
      .filter(d => typeof d.score === 'number')
      .sort((a, b) => a.score - b.score)
      .slice(0, 3);
    return '<div class="refine-row">'
      + lowest.map(d => `<button class="refine-btn" onclick="refine('${d.key}')">${d.label}</button>`).join('')
      + '</div>';
  }

  const SURPRISES = [
    "Take me somewhere I've never heard of",
    "The weirdest place to sleep on the planet",
    "A place that belongs in a movie",
    "Somewhere so remote there's no WiFi",
    "The most dramatic landscape with a bed in it",
    "A place that will make my friends jealous",
    "Something I'd never think to book myself",
    "Where nobody else is going right now",
  ];

  function surprise() {
    const text = SURPRISES[Math.floor(Math.random() * SURPRISES.length)];
    const ta = document.getElementById(twoPersonMode ? 'query_a' : 'query');
    ta.value = text;
    grow(ta);
    search();
  }

  function suggest(btn) {
    const ta = document.getElementById(twoPersonMode ? 'query_a' : 'query');
    ta.value = btn.textContent;
    grow(ta);
    search();
  }

  function grow(el) {
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 160) + 'px';
  }

  function onKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); search(); }
  }

  function applyBudget() {
    const val = parseFloat(document.getElementById('budgetInput').value);
    if (!val || val <= 0) return;
    if (!lastScores) return;
    search({ scores_override: lastScores, budget_usd: val, avoidances_list: lastAvoidances });
  }

  async function search(overrides) {
    const btn = document.getElementById('btn');
    const out = document.getElementById('results');

    let query, query_b, displayLabel;
    if (twoPersonMode) {
      query   = document.getElementById('query_a').value.trim();
      query_b = document.getElementById('query_b').value.trim();
      if (!query && !query_b) return;
      lastQuery = query;
      displayLabel = query_b
        ? `Person A: "${query}" &amp; Person B: "${query_b}"`
        : `Person A: "${query}"`;
    } else {
      query = document.getElementById('query').value.trim();
      if (!query) return;
      lastQuery = query;
      displayLabel = `"${query}"`;
    }

    btn.disabled = true;
    out.innerHTML = `
      <div class="loading">
        <div class="spinner"></div>
        <p class="loading-title">${overrides ? 'Adjusting your results…' : twoPersonMode ? 'Finding your perfect compromise…' : 'Reading your vibe…'}</p>
        <p class="loading-sub">Matching hotels, checking live availability${overrides ? '' : ', writing pitches'}</p>
      </div>`;
    out.scrollIntoView({ behavior: 'smooth', block: 'start' });

    try {
      const payload = {
        query,
        avoidances: document.getElementById('avoidances').value.trim(),
        ...overrides,
      };
      if (twoPersonMode && query_b && !overrides) payload.query_b = query_b;

      const resp = await fetch('/match', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!resp.ok) throw new Error(await resp.text());
      const data = await resp.json();
      allHotels      = data.hotels;
      lastScores     = data.scores;
      lastBudget     = data.budget_usd || 0;
      lastAvoidances = data.avoidances_list || [];
      lastCheckIn    = data.check_in  || '';
      lastCheckOut   = data.check_out || '';
      lastDisplayLabel = displayLabel;
      if (!overrides || !overrides.scores_override) baseScores = data.scores;

      if (!allHotels.length) {
        out.innerHTML = '<div class="error">No matches found.</div>';
        return;
      }

      currentPage = 0;
      renderPage(0);
    } catch(e) {
      out.innerHTML = `<div class="error">Something went wrong: ${e.message}</div>`;
    } finally {
      btn.disabled = false;
    }
  }

  function paginationHtml(current, total) {
    const pages = new Set([0, total - 1, current - 1, current, current + 1]
      .filter(p => p >= 0 && p < total));
    const sorted = [...pages].sort((a, b) => a - b);
    let nums = '';
    let prev = -1;
    for (const p of sorted) {
      if (p - prev > 1) nums += '<span class="page-ellipsis">…</span>';
      nums += `<button class="page-num${p === current ? ' active' : ''}" onclick="goToPage(${p})">${p + 1}</button>`;
      prev = p;
    }
    return `<div class="pagination">
      <button class="page-btn" onclick="goToPage(${current - 1})" ${current === 0 ? 'disabled' : ''}>← Prev</button>
      <div class="page-nums">${nums}</div>
      <button class="page-btn" onclick="goToPage(${current + 1})" ${current >= total - 1 ? 'disabled' : ''}>Next →</button>
    </div>`;
  }

  function renderPage(page) {
    currentPage = page;
    const out = document.getElementById('results');
    const total = Math.ceil(allHotels.length / PAGE_SIZE);
    const slice = allHotels.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

    out.innerHTML = `
      <div class="results-inner">
        <div class="results-label">
          <h2>Your top matches</h2>
          <p>Based on: ${lastDisplayLabel} &nbsp;·&nbsp; ${allHotels.length} hotels found</p>
        </div>
        <div class="budget-bar">
          <span class="budget-bar-label">Results too pricey?</span>
          <span class="budget-bar-label">·  Max total budget:</span>
          <input class="budget-input" id="budgetInput" type="number" min="0" step="50"
            placeholder="e.g. 800" onkeydown="if(event.key==='Enter') applyBudget()">
          <span class="budget-bar-label">USD</span>
          <button class="budget-apply" onclick="applyBudget()">Apply</button>
        </div>
        <div class="cards" id="cards">${slice.map((h, i) => card(h, page * PAGE_SIZE + i)).join('')}</div>
        ${paginationHtml(page, total)}
      </div>`;

    // Lazy-load availability for this page if not yet checked
    const needsAvail = slice.some(h => h.available === undefined);
    if (needsAvail) loadPageAvailability(page, slice);
  }

  async function loadPageAvailability(page, slice) {
    try {
      const resp = await fetch('/avail', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ hotels: slice, check_in: lastCheckIn, check_out: lastCheckOut }),
      });
      const avails = await resp.json();
      avails.forEach((a, i) => {
        if (a) Object.assign(allHotels[page * PAGE_SIZE + i], a);
      });
      // Only re-render if we're still on the same page
      if (currentPage === page) {
        const cards = document.getElementById('cards');
        if (cards) {
          const updated = allHotels.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
          cards.innerHTML = updated.map((h, i) => card(h, page * PAGE_SIZE + i)).join('');
        }
      }
    } catch(e) { /* availability check failed silently */ }
  }

  function goToPage(page) {
    const total = Math.ceil(allHotels.length / PAGE_SIZE);
    if (page < 0 || page >= total) return;
    renderPage(page);
    document.getElementById('results').scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  function criteria(h) {
    const dims = [
      ['Romance',        h['Romance']],
      ['Luxury',         h['Luxury']],
      ['Novelty',        h['Novelty']],
      ['Remoteness',     h['Remoteness']],
      ['Intensity',      h['Intensity']],
      ['Visual Awe',     h['Visual Awe']],
      ['Story',          h['Story Worthiness']],
    ];
    return '<div class="criteria">' + dims.map(([name, v]) => {
      if (typeof v !== 'number') return '';
      const pct = v * 10;
      return `<div class="crit">
        <span class="crit-name">${name}</span>
        <div class="crit-bar-wrap"><div class="crit-bar" style="width:${pct}%"></div></div>
        <span class="crit-pct">${pct}%</span>
      </div>`;
    }).join('') + '</div>';
  }

  function availBadge(h) {
    if (h.available === true)  return `<span class="avail-badge avail-yes">✓ Available RIGHT NOW</span>`;
    if (h.available === false) return `<span class="avail-badge avail-no">✗ No rooms found for these dates</span>`;
    return '';
  }

  const ROLE_META = {
    safe:     { icon: '🛡', label: 'The Safe Choice' },
    gem:      { icon: '💎', label: 'The Hidden Gem'  },
    wildcard: { icon: '🎲', label: 'The Wildcard'    },
  };

  function card(h, i) {
    const role = h._role || 'match';
    const isEditorial = role !== 'match';
    const meta = isEditorial
      ? ROLE_META[role]
      : { icon: '✦', label: `#${h._rank || i + 1} Best Match` };

    const photoSrc = h.live_photo || h.Photo || '';
    const photo = photoSrc
      ? `<img class="card-img" src="${photoSrc}" alt="${h.Name}"
             onerror="this.outerHTML='<div class=card-img-placeholder>🏨</div>'">`
      : `<div class="card-img-placeholder">🏨</div>`;

    const livePrice = h.live_price || h['Price (total)'];
    const price = livePrice ? `<span class="card-price">Est. ~${livePrice}</span>` : `<span></span>`;

    const name = h.Name || '';
    const dest = h.Destination || '';
    const gq = encodeURIComponent(name + ' ' + dest);
    const url = h.booking_url || ('https://www.google.com/travel/hotels?q=' + gq);

    const pitchHtml = h.pitch
      ? `<p class="card-pitch">${h.pitch}</p>`
      : '';

    return `
      <div class="card" data-role="${role}">
        <div class="card-banner">
          <span class="banner-icon">${meta.icon}</span>
          ${meta.label}
        </div>
        <div class="card-main">
          ${photo}
          <div class="card-body">
            <div class="card-header">
              <div>
                <div class="card-name">${h.Name}</div>
                <div class="card-dest">${h.Destination}</div>
              </div>
              <div class="match-pill">${h['Match %']}% match</div>
            </div>
            ${availBadge(h)}
            ${criteria(h)}
            ${pitchHtml}
            ${refineButtons(h)}
            <div class="card-footer">
              ${price}
              <a class="book-link" href="${url}" target="_blank" rel="noopener">Book Now →</a>
            </div>
          </div>
        </div>
      </div>`;
  }
</script>
</body>
</html>"""


@app.route("/")
def index():
    return render_template_string(HTML)


@app.route("/health")
def health():
    return jsonify({
        "hotels_file_exists": HOTELS_FILE.exists(),
        "hotels_count": len(json.loads(HOTELS_FILE.read_text(encoding="utf-8"))) if HOTELS_FILE.exists() else 0,
        "anthropic_key_set": bool(ANTHROPIC_API_KEY),
        "serpapi_key_set": bool(SERPAPI_KEY),
    })


@app.route("/match", methods=["POST"])
def match():
    try:
        return _match_inner()
    except Exception as exc:
        import traceback as tb
        return jsonify({"error": str(exc), "trace": tb.format_exc()}), 500


def _match_inner():
    if not HOTELS_FILE.exists():
        return jsonify({"error": "hotels.json not found — run travellingai.py first"}), 500

    data = request.get_json(force=True)
    user_input = (data.get("query") or "").strip()
    if not user_input:
        return jsonify([])

    from datetime import date, timedelta
    today     = date.today()
    check_in  = str(today + timedelta(days=10))
    check_out = str(today + timedelta(days=14))

    hotels = json.loads(HOTELS_FILE.read_text(encoding="utf-8"))

    avoid_text      = (data.get("avoidances") or "").strip()
    query_b         = (data.get("query_b") or "").strip()
    scores_override = data.get("scores_override")  # dict of {dim: value} from refine

    if scores_override:
        # Refine mode: skip Claude, use boosted scores directly
        user_scores = {k: int(scores_override.get(k, 5)) for k in _SCORE_KEYS}
        budget_usd  = float(data.get("budget_usd") or 0)
        avoidances  = data.get("avoidances_list") or []
        pitch_input = user_input
    elif query_b:
        # Two-person mode: score each person separately then average
        with ThreadPoolExecutor(max_workers=2) as ex:
            fa = ex.submit(feeling_to_scores, f"{user_input}\n\nThings to avoid: {avoid_text}" if avoid_text else user_input)
            fb = ex.submit(feeling_to_scores, query_b)
            scores_a = fa.result()
            scores_b = fb.result()

        budget_a = scores_a.pop("budget_usd", 0)
        budget_b = scores_b.pop("budget_usd", 0)
        avoid_a  = scores_a.pop("avoidances", [])
        avoid_b  = scores_b.pop("avoidances", [])

        user_scores = {k: round((scores_a.get(k, 5) + scores_b.get(k, 5)) / 2) for k in _SCORE_KEYS}
        budget_usd  = min(b for b in [budget_a, budget_b] if b > 0) if any([budget_a, budget_b]) else 0
        avoidances  = list(set(avoid_a + avoid_b))
        pitch_input = f"Person A wants: {user_input}\nPerson B wants: {query_b}"
    else:
        full_input  = f"{user_input}\n\nThings to avoid: {avoid_text}" if avoid_text else user_input
        user_scores = feeling_to_scores(full_input)
        budget_usd  = user_scores.pop("budget_usd", 0)
        avoidances  = user_scores.pop("avoidances", [])
        pitch_input = user_input

    if budget_usd > 0:
        filtered = [
            h for h in hotels
            if _parse_price(h.get("Price (total)", "")) <= budget_usd
            or _parse_price(h.get("Price (total)", "")) == 0
        ]
        hotels = filtered if filtered else hotels

    if avoidances:
        filtered = [h for h in hotels if _passes_avoidance(h, avoidances)]
        hotels = filtered if len(filtered) >= 5 else hotels  # fall back if too aggressive

    compute_match(hotels, user_scores)

    if scores_override:
        by_match = sorted(hotels, key=lambda h: h.get("Match %", 0), reverse=True)
        role_labels = ["safe", "gem", "wildcard"]
        results = []
        for i, h in enumerate(by_match):
            role = role_labels[i] if i < 3 else "match"
            entry = {**h, "_role": role}
            if i >= 3:
                entry["_rank"] = i + 1
            results.append(entry)
        editorial = []
    else:
        results = select_all(hotels)
        editorial = results[:3]

    # Only check availability for first page (10 hotels) — rest loaded lazily
    page1 = results[:10]
    with ThreadPoolExecutor(max_workers=13) as ex:
        pitch_futures = {
            ex.submit(generate_pitch, pitch_input, h, h["_role"]): i
            for i, h in enumerate(editorial)
        }
        avail_futures = {
            ex.submit(check_availability, h, check_in, check_out, 2, 1): i
            for i, h in enumerate(page1)
        }
        for f in as_completed(pitch_futures):
            editorial[pitch_futures[f]]["pitch"] = f.result()
        for f in as_completed(avail_futures):
            page1[avail_futures[f]].update(f.result())

    for h in results:
        h["_check_in"]  = check_in
        h["_check_out"] = check_out

    return jsonify({
        "hotels": results,
        "scores": user_scores,
        "budget_usd": budget_usd,
        "avoidances_list": avoidances,
        "check_in": check_in,
        "check_out": check_out,
    })


@app.route("/avail", methods=["POST"])
def avail():
    data = request.get_json(force=True)
    hotels_data = data.get("hotels") or []
    check_in  = data.get("check_in", "")
    check_out = data.get("check_out", "")
    results = [None] * len(hotels_data)
    with ThreadPoolExecutor(max_workers=10) as ex:
        futures = {
            ex.submit(check_availability, h, check_in, check_out, 2, 1): i
            for i, h in enumerate(hotels_data)
        }
        for f in as_completed(futures):
            results[futures[f]] = f.result()
    return jsonify(results)


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    print(f"Open http://localhost:{port} in your browser")
    app.run(debug=False, host="0.0.0.0", port=port)
